show databases;

-- CREATE DATABASE JOB_APP;

use JOB_APP;

-- INFO QUERIES START

select * from information_schema.tables where table_schema = 'JOB_APP' order by create_time asc;
select TABLE_SCHEMA, TABLE_NAME, TABLE_ROWS, CREATE_TIME from information_schema.tables where table_schema = 'JOB_APP' order by create_time asc;
select * from information_schema.columns where table_schema = 'JOB_APP'; -- use to check if datatypes for person table updated.
-- Returns number of tables
select count(*) from information_schema.tables 
where table_schema = 'JOB_APP';

-- Check constraint types
SELECT 
    CONSTRAINT_NAME,
    TABLE_NAME,
    CONSTRAINT_TYPE
FROM 
    information_schema.TABLE_CONSTRAINTS
WHERE 
    TABLE_SCHEMA = 'JOB_APP';
    
-- INFO QUERIES END

CREATE TABLE POTENTIAL_EMPLOYEE(
	PotEmp_ID		INT PRIMARY KEY AUTO_INCREMENT,
	PotEmpUsername		VARCHAR(20),
	PotEmpPassword		VARCHAR(20)
);
SELECT * FROM POTENTIAL_EMPLOYEE;
ALTER TABLE POTENTIAL_EMPLOYEE
MODIFY COLUMN PotEmpPassword VARCHAR(100);

CREATE TABLE COMPANY(
	Company_ID		INT PRIMARY KEY AUTO_INCREMENT,
	CompanyName		VARCHAR(100)
);
SELECT * FROM COMPANY;

CREATE TABLE JOB_APPLYING_ACCOUNT(
	JAA_ID			INT AUTO_INCREMENT,
	JAA_Username		VARCHAR(50),
	JAA_Password		VARCHAR(50),

	PotEmp_ID		INT,
	Company_ID		INT,
	
	PRIMARY KEY (JAA_ID), -- Should this include PotEmpID
	FOREIGN KEY (PotEmp_ID) REFERENCES POTENTIAL_EMPLOYEE(PotEmp_ID) ON DELETE CASCADE,
	FOREIGN KEY (Company_ID) REFERENCES COMPANY(Company_ID) ON DELETE CASCADE
);

CREATE TABLE JOB(
	Job_ID			INT PRIMARY KEY AUTO_INCREMENT,
	JobPosition		VARCHAR(50),
	Platform		VARCHAR(50),
	Notes			TEXT,

	Company_ID		INT,
	
	FOREIGN KEY (Company_ID) REFERENCES COMPANY(Company_ID) ON DELETE CASCADE
);

CREATE TABLE APPLIES(
	PotEmp_ID		INT,
	Job_ID			INT,
	DateApplied		DATE,

	PRIMARY KEY (PotEmp_ID, Job_ID),
	FOREIGN KEY (PotEmp_ID) REFERENCES POTENTIAL_EMPLOYEE(PotEmp_ID) ON DELETE CASCADE,
	FOREIGN KEY (Job_ID) REFERENCES JOB(Job_ID) ON DELETE CASCADE
);

CREATE TABLE STATUS(
	Status_ID		INT PRIMARY KEY AUTO_INCREMENT,
	StatusDate		DATE,
	StatusType		ENUM("ACCEPTED", "REJECTED", "INTERVIEWING", "IN_PROGRESS", "NO_RESPONSE"),

	Job_ID			INT,

	FOREIGN KEY (Job_ID) REFERENCES JOB(Job_ID) ON DELETE CASCADE
);

CREATE TABLE URLS(
	URL_ID			INT PRIMARY KEY AUTO_INCREMENT,
	URL_TYPE		ENUM("PRIMARY", "OPTIONAL"),
	URL_LINK		TEXT,

	Job_ID			INT,

	FOREIGN KEY (Job_ID) REFERENCES JOB(Job_ID) ON DELETE CASCADE
);
